name: Node.js CI

on:
  push:
    branches: [ develop ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'coretto'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew build
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            geeksven/gs-barcody
          tags: |
            type=sha
            latest
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: src/main/docker/Dockerfile.jvm
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: echo tags
        run: echo ${{ steps.vars.outputs.sha_short }}
#      - name: deploy to cluster
#        uses: steebchen/kubectl@v2.0.0
#        with: # defaults to latest kubectl binary version
#          config: ${{ secrets.KUBE_CONFIG_DATA }}
#          command: set image --record deployment/gs-hello gs-hello=geeksven/gs-hello:sha-${{ steps.vars.outputs.sha_short }} -n geeksven-dev
#      - name: verify deployment
#        uses: steebchen/kubectl@v2.0.0
#        with:
#          config: ${{ secrets.KUBE_CONFIG_DATA }}
#          version: v1.21.0 # specify kubectl binary version explicitly
#          command: rollout status deployment/gs-hello -n geeksven-dev